[package]
name = "rust_kernel"
version = "0.1.0"
authors = ["Dennis Restle <dennis.restle@htwg-konstanz.de"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
bitflags = "0.7.0"
multiboot2 = "0.1.0"
once = "0.3.2"
rlibc = "1.0"
spin = "0.4.5"
volatile = "0.1.0"
x86_64 = "0.1.2"
bit_field = "=0.7.0"


[dependencies.lazy_static]
version = "0.2.4"
features = ["spin_no_std"]

[dependencies.bump_allocator]
path = "libs/bump_allocator"

[dependencies.hole_list_allocator]
path = "libs/hole_list_allocator"
